#define LOGPFX_CLASS_ENGINE 					"[ENGINE]  "
#define LOGPFX_CLASS_VULKAN_RENDERING_ENGINE 	"[VULKAN]  "
#define LOGPFX_CLASS_SCENE_LOADER 				"[SCENE_L] "
#define LOGPFX_CLASS_LOGGER						"[LOGGER]  "
#define LOGPFX_CLASS_ASSET_MANAGER				"[ASSET_M] "
#define LOGPFX_CLASS_SCENE						"[SCENE]   "
#define LOGPFX_CLASS_TEXTURE					"[TEXTURE] "
#define LOGPFX_CLASS_FONT						"[FONT]    "

#define LOGPFX_NONE "[???] "

#ifndef LOGPFX_CURRENT
	#define LOGPFX_CURRENT LOGPFX_NONE
#endif