#define LOGPFX_CLASS_ENGINE "[ENGINE] "
#define LOGPFX_CLASS_VULKAN_RENDERING_ENGINE "[VRE] "
#define LOGPFX_CLASS_SCENE_LOADER "[SCENELDR] "
#define LOGPFX_CLASS_LOGGER "[LOGGER] "

#define LOGPFX_NONE "[???] "

#ifndef LOGPFX_CURRENT
	#define LOGPFX_CURRENT LOGPFX_NONE
#endif